### ISSUE TITLE
static cURL

### ISSUE THREAD

**Issue by ghost** [cygwinports/mingw64-x86_64-curl#1]
this package does contain a static library:

~~~
usr/x86_64-w64-mingw32/sys-root/mingw/lib/libcurl.a
~~~

however it has a couple of problems. first, the library depends on nghttp2, but
no static nghttp2 is available.

Second, even if a static nghttp2 was available, the static cURL here has not
been built to utilize it. that would require building cURL with
`-DNGHTTP2_STATICLIB`.

https://github.com/curl/curl/issues/2516

## workaround

its available here:

https://curl.haxx.se/windows

**Comment by cup** [comment]
https://github.com/chocolatey/chocolatey-coreteampackages/issues/1241
https://github.com/curl/curl/issues/2516
https://github.com/cygwinports/mingw64-x86_64-curl/issues/1
https://github.com/msys2/MINGW-packages/issues/3538

**Comment by cup** [comment]
https://github.com/cygwinports/mingw64-x86_64-nghttp2/issues/1

**Comment by yselkowitz** [comment]
This will be fixed in cygport.
